.PHONY: clean All

All:
	@echo "----------Building project:[ kv2clientApplication - Debug ]----------"
	@cd "kv2clientApplication" && $(MAKE) -f  "kv2clientApplication.mk" PreBuild && $(MAKE) -f  "kv2clientApplication.mk" && $(MAKE) -f  "kv2clientApplication.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ kv2clientApplication - Debug ]----------"
	@cd "kv2clientApplication" && $(MAKE) -f  "kv2clientApplication.mk" clean
